/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lankaocr.formwindows;

import com.lankaocr.actions.DiffActions;
import com.lankaocr.actions.OcrActions;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

import javax.swing.*;
import java.awt.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author kasun
 */
public class OutputPreviewWindow extends javax.swing.JFrame {

    private static String htmlFileName;
    private static String textFileName;
    private static String htmlFilePath;
    private static String textOcrOutput;
    private org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(this.getClass());

    /**
     * Creates new form CorrectionsView
     */
    public OutputPreviewWindow() {
        initComponents();

    }

    public void loadFile(String hocrOutput, String textOutput, String htmlOutputFileName, String textoutputFileName, String inputFileDirectory) throws IOException {

        htmlFileName = htmlOutputFileName;
        htmlFilePath = inputFileDirectory;
        textFileName = textoutputFileName;
        textOcrOutput = textOutput;

        //Normalize the hocr Output
        OcrActions instance = new OcrActions();

        GraphicsEnvironment e = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Font[] fonts = e.getAllFonts(); // Get the fonts
        for (Font f : fonts) {
            jComboBox1.addItem(f.getName());
        }

        File file = new File(htmlFilePath + "\\" + htmlFileName);
        instance.normalizeOutputText(file);
        htmlView.setEditable(false);
        htmlView.setFont(new Font("Iskoola Pota", 0, 18));
        htmlView.setContentType("text/html;charset=utf-8");
        htmlView.setPage(file.toURI().toURL());
        htmlView.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.TRUE);
        jScrollPane1.add(htmlView);

    }

    private StringBuilder readOriginalInputText(String originalFilePath) {
        File textFile = new File(originalFilePath);

        StringBuilder fileContent = new StringBuilder();

        try {
            BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(textFile), "UTF-8"));
            String st;
            while ((st = br.readLine()) != null) {
                fileContent.append(st);
            }
            br.close();
        } catch (FileNotFoundException ex) {
            log.error(ex);
        } catch (IOException ex) {
            log.error(ex);
        }

        log.info("File Conent: " + fileContent.toString());

        return fileContent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        htmlView = new javax.swing.JEditorPane();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnGenerateDiff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Output Preview");
        setName("Output Preview"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeOutputPreviewHandler(evt);
            }
        });

        htmlView.setEditorKit(null);
        htmlView.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(htmlView);

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Iskoola Pota", 1, 12)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Font : ");

        btnGenerateDiff.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGenerateDiff.setText("Generate Diff Report");
        btnGenerateDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateDiffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 762, Short.MAX_VALUE)
                        .addComponent(btnGenerateDiff, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel)
                    .addComponent(btnGenerateDiff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnSave.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static int currrentWordPosition;
    public static String currentWord = "";

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        File htmlFile = new File(htmlFilePath + "\\" + htmlFileName);
        File wordFile = new File(htmlFilePath + "\\" + htmlFileName.substring(0, htmlFileName.length() - 5) + ".doc");
        if (htmlFile.renameTo(wordFile)) {
            log.info("final output written to : " + htmlFilePath + "  with name : " + htmlFileName + ".doc");
        } else {
            log.info("Failed to rename the html file to .doc");
        }

        log.info("*********** Writing complete *************");

        this.dispose();


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        File htmlFile = new File(htmlFilePath + "\\" + htmlFileName);
        File textFile = new File(htmlFilePath + "\\" + textFileName);
        File diffFile = new File(htmlFilePath + "\\" + "Diff_report_" + htmlFileName.substring(0, htmlFileName.length() - 5) + ".log");

       if (htmlFile.delete()) {
            log.info("deleted file without saving " + htmlFile.getName());
        } else {
            log.info("failed to delete file before cloasing output preview window File Name:  " + htmlFile.getName());
        }
        
        if (textFile.delete()) {
            log.info("deleted file without saving " + textFile.getName());
        } else {
            log.info("failed to delete file before cloasing output preview window File Name:  " + textFile.getName());
        }
        
        if (diffFile.delete()) {
            log.info("deleted file without saving " + diffFile.getName());
        } else {
            log.info("failed to delete file before cloasing output preview window File Name:  " + diffFile.getName());
        }

        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        htmlView.setFont(new Font(jComboBox1.getSelectedItem().toString(), 0, 18));
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void closeOutputPreviewHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeOutputPreviewHandler

        File file = new File(htmlFilePath + "\\" + htmlFileName);
        File textFile = new File(htmlFilePath + "\\" + textFileName);
        File diffFile = new File(htmlFilePath + "\\" + "Diff_report_" + htmlFileName.substring(0, htmlFileName.length() - 5) + ".log");

        if (file.delete()) {
            log.info("deleted file without saving " + file.getName());
        } else {
            log.info("failed to delete file before cloasing output preview window File Name:  " + file.getName());
        }
        
        if (textFile.delete()) {
            log.info("deleted file without saving " + textFile.getName());
        } else {
            log.info("failed to delete file before cloasing output preview window File Name:  " + textFile.getName());
        }
        
         if (diffFile.delete()) {
            log.info("deleted file without saving " + diffFile.getName());
        } else {
            log.info("failed to delete file before cloasing output preview window File Name:  " + diffFile.getName());
        }

        this.dispose();
    }//GEN-LAST:event_closeOutputPreviewHandler

    private void btnGenerateDiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateDiffActionPerformed
        
        StringBuilder originalText = readOriginalInputText(htmlFilePath + "\\" + "Latest_input.txt");
        String diffReportFile = htmlFilePath + "\\" + "Diff_report_" + htmlFileName.substring(0, htmlFileName.length() - 5) + ".log";
        DiffActions diffAction = new DiffActions();
        diffAction.createDiffReport(originalText.toString(), textOcrOutput, diffReportFile);
        
    }//GEN-LAST:event_btnGenerateDiffActionPerformed

    public String selectWord(int selection) {
        String currentSelectedWord = "";

        Document doc = Jsoup.parse(htmlView.getText(), "UTF-8");
        Elements words = doc.select("span.ocrx_word");
        int noOfWords = words.size();

        if (selection < noOfWords && selection > 0) {
            currentSelectedWord = words.get(selection).text();
        } else if (selection < noOfWords && selection < 0) {
            currrentWordPosition = noOfWords + selection;
            currentSelectedWord = words.get(currrentWordPosition).text();
        } else if (selection < noOfWords && selection == 0) {
            currentSelectedWord = words.get(currrentWordPosition).text();
        } else {
            currrentWordPosition = selection - noOfWords;
            currentSelectedWord = words.get(currrentWordPosition).text();
        }

        return currentSelectedWord;

    }

//    /**
//     * @param args the command line arguments
//     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputPreviewWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputPreviewWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputPreviewWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputPreviewWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutputPreviewWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGenerateDiff;
    private javax.swing.JButton btnSave;
    private javax.swing.JEditorPane htmlView;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
